Dc 03 news blog
mayurdawnge45/mayur-portfolio pull request #7
Opened 2021-08-24 11:05 UTC by mayurdawnge45

My Personnel portfolio news blog section has been completed

2021-08-26 01:45 UTC, akash-dhande requested changes
small change

2021-08-26 01:45 UTC, akash-dhande commented on index.html
> +            <div class="right-maskgroup"><img src="assets/images/53 1817143482.png" alt=""></div>
File naming is wrong

2021-08-26 01:46 UTC, akash-dhande commented
Keep consistency in PR title "Dc 03 news blog" > "DC-03 News Blog"

2021-08-26 01:47 UTC, akash-dhande commented
Add ticket url in PR details

2021-08-26 01:48 UTC, akash-dhande commented
Ticket: [TICKET-URL]
- Description detail 01
- Description detail 02
  - Description sub detail 02.01
- Description detail 03

Thanks

2021-09-03 12:15 UTC, akash-dhande commented
> * ription detail 01
> * Description detail 02
>   
>   * Description sub detail 02.01
> * Description detail 03
> 
> Thanks

Updated the description.

2021-09-03 12:32 UTC, mayurdawnge45 commented on index.html
> +            <div class="right-maskgroup"><img src="assets/images/53 1817143482.png" alt=""></div>
Hi @akash-dhande
https://dhandecreative.atlassian.net/browse/DC-3 
I have changed the file name and its Dependences.

Thanks.

2021-09-03 13:30 UTC, akash-dhande approved these changes

2021-09-03 13:30 UTC, merged