Dc 09 contact section
mayurdawnge45/mayur-portfolio pull request #8
Opened 2021-08-31 11:31 UTC by mayurdawnge45

contact section and Static page has been completed.

2021-08-31 11:37 UTC, akash-dhande commented
Branch has wrong base, following old commints.

2021-08-31 13:00 UTC, akash-dhande requested changes
wrong base, missing PR details

2021-09-03 13:48 UTC, akash-dhande requested changes

2021-09-03 13:48 UTC, akash-dhande commented on index.html
> +>>>>>>> master
Hi @mayurdawnge45, you missed conflict marks.

2021-09-03 13:49 UTC, akash-dhande commented
Also please update PR title and description.

2021-09-03 14:06 UTC, mayurdawnge45 commented
Hi @akash-dhande I have Updated some work related to this ticket https://dhandecreative.atlassian.net/browse/DC-9
please merged this ticket

Thanks

2021-09-04 01:00 UTC, akash-dhande approved these changes

2021-09-04 01:00 UTC, merged